# Build settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site settings
title: DevFest Miage Gi 2014
email: infos@gdgmiagegi.ci
description: "DevFest Miage gi est un évènement qui se deroule chaque année et à pour but de promouvoir l'utilisation des technologies Google en Côte d'Ivoire "
baseurl: ""
locale: "fr"
url: http://gdgmiagegilab.github.io"
permalink: /blog/:title
googleAnalyticsTrackingId: "UA-49492619-3"
googleAnalyticsSiteUrl: "http://gdgmiagegilab.github.io"

# Location block
eventLocationName: "Abidjan"
eventLocationAddress: "Abidjan"
eventStartTime: "2014-11-28T08:00"
eventStartTimeHumanReadable: "08:00"
eventEndTime: "2014-11-30T20:00"
eventEndTimeHumanReadable: "20:00"
eventPlaceCoordinates: "5.347075, -3.985300"
mapCenterCoordinates: "5.343892, -3.988229"
mapMobileCenterCoordinates: "-5.343892, -3.988229"

# Logistics Location Block
logisticsMapCenterCoordinates: "5.343892, -3.988229"
logisticsMapMobileCenterCoordinates: "5.343892, -3.988229"

#Tweets feed
twitterHashTag: "devfestmgi #itshackademic #gsassa"
twitterFeed: ""

# Subscribe
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"

# Documents
c4pUrl: "https://www.eventbrite.fr/e/gdg-devfest-civ-2014-tickets-14426286411"
c4sponsorsUrl: ""

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, dart, polymer, android wear, miage, inphb, ambassador"
twitterAccount: "@GDG_MiageGi"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Header
eventDate: "Novembre - Décembre 2014"
typeoutTextValues: '"Season", "Miage Gi", "Abidjan", "Bouaké", "Yamoussoukro", "Africa", "Universités",  "Agitel", "Bassam", "INPHB", "Bingerville"'

# About Event Block
eventName: "DevFest GDG Miage Gi"

# Team Block
aboutUs: Les services Google sont devenus incontournable sur le Web.Le nombre d'innovations technologiques et des industries IT basé sur les produits Google est énorme. Il est difficile d'apprendre à connaître toutes les technologies Google. C'est pourquoi les personnes passionnées ont commencé à se rassembler en petits groupes locaux afin de partager leur expérience. Plus tard ces groupes ont été appelés groupes de développeurs de Google. Notre Equipe ce presente comme suit.

# Speakers List Block
showSessions: true
thumbnailsFolder: /img/speakers/

# Footer
gplusFollowUsUrl: "https://plus.google.com/b/102444623953913144164"
twitterFollowUsUrl: "https://twitter.com/intent/user?screen_name=GDG_MiageGi"
fbFollowUsUrl: "https://facebook.com/Devfestgdgmiagegi"

# Blog
blogCommentsEnabled: true
discusShortName: "devfestmgi"